---
Name: staffdirectoryconfig
---
Dynamic\Staff\Pages\StaffMember:
  extensions:
    - LittleGiant\CatalogManager\Extensions\CatalogPageExtension
  parent_classes:
    - Dynamic\Staff\Pages\StaffDirectory
  sort_column: false
